tag @a[tag=Turn] remove Turn
tag @a[tag=BlueCaptain] remove BlueCaptain
tag @a[tag=YellowCaptain] remove YellowCaptain
tag @a[tag=GreenCaptain] remove GreenCaptain
tag @a[tag=RedCaptain] remove RedCaptain
tag @a[tag=Captain] remove Captain

function utility:waterstop/enable

# generated by cleancalc.js
fill -13 -13 45 12 14 70 minecraft:air
kill @e[type=!minecraft:player,x=-13,y=0,z=45,dx=25,dy=14,dz=25]
kill @e[type=!minecraft:player,x=-13,y=0,z=45,dx=25,dy=14,dz=25]

#TODO: maybe load other sumos
setblock -13 0 45 minecraft:structure_block{author:"ffaen",mode:"LOAD",name:"chunkwars:lobby/sumo"}
setblock -13 1 45 minecraft:redstone_block

schedule function utility:waterstop/disable 1s

# unlock signs that deal with player teams, so players can leave their team
execute as @e[type=marker,tag=GamestateTeams] at @s run function utility:sign/unlock/this