function main:waterstop/enable

# generated by cleancalc.js
fill -13 -13 45 12 14 70 minecraft:air
kill @e[type=!minecraft:player,x=-13,y=0,z=45,dx=25,dy=14,dz=25]
kill @e[type=!minecraft:player,x=-13,y=0,z=45,dx=25,dy=14,dz=25]

setblock -13 0 45 minecraft:structure_block{author:"ffaen",mode:"LOAD",name:"chunkwars:lobby/sumo"}
setblock -13 1 45 minecraft:redstone_block

schedule function main:waterstop/disable 1s

function main:misc/unlock_signs