const start_x = -105
const start_y = 0
const start_z = 921

const end_x = 102
const end_y = 229
const end_z = 1128

const MAX_CHUNK_SIZE = 32 // (x3 dimentions = 32768)

console.log('# generated by cleancalc.js')

for (let x = start_x; x < end_x; x += MAX_CHUNK_SIZE) {
    let cap_x = Math.min(x+MAX_CHUNK_SIZE-1, end_x)

    for (let y = start_y; y < end_y; y += MAX_CHUNK_SIZE) {
        let cap_y = Math.min(y+MAX_CHUNK_SIZE-1, end_y)

        for (let z = start_z; z < end_z; z += MAX_CHUNK_SIZE) {
            let cap_z = Math.min(z+MAX_CHUNK_SIZE-1, end_z)

            console.log(`fill ${x} ${y} ${z} ${cap_x} ${cap_y} ${cap_z} minecraft:air`)
        }

    }

}

console.log(`kill @e[type=!player,x=${start_x},y=${start_y},z=${start_z},dx=${end_x-start_x},dy=${end_y-start_y},dz=${end_z-start_z}]`)